// Code generated by goctl. DO NOT EDIT.
package types

type CalReq struct {
	Id       string  `json:"id"`
	Jwt      string  `json:"jwt"`
	WorkHour float32 `json:"workHour"`
}

type CalResp struct {
	WageBeforeTax float32 `json:"wageBeforeTax"`
	WageAfterTax  float32 `json:"wageAfterTax"`
	ActualWage    float32 `json:"actualWage"`
}
