version: '3'
services:
  golang-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 10001:10001
    depends_on:
      - redis
      - mongodb
      - minio
      - etcd

  redis:
    image: redis
    ports:
      - 6379:6379

  mongodb:
    image: mongo
    ports:
      - 27017:27017

  minio:
    image: minio/minio
    command: server /data
    environment:
      - MINIO_ACCESS_KEY=RhHLYIdViKn4Fzw2
      - MINIO_SECRET_KEY=C1wvv82jDdyaP7AbD6hM89x0e7RQGa9N
    ports:
      - 9000:9000
    volumes:
      - ./data:/data