// Code generated by goctl. DO NOT EDIT.
// Source: wage.proto

package server

import (
	"context"

	"Table/app/financial/cmd/rpc/internal/logic"
	"Table/app/financial/cmd/rpc/internal/svc"
	"Table/app/financial/cmd/rpc/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) CalWage(ctx context.Context, in *pb.CalReq) (*pb.CalResp, error) {
	l := logic.NewCalWageLogic(ctx, s.svcCtx)
	return l.CalWage(in)
}
