// Code generated by goctl. DO NOT EDIT.
package types

type UserLoginReq struct {
	Name     string `json:"name""`
	Password string `json:"password"`
}

type UserLoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type UserInfoReq struct {
	Id string `json:"id"`
}

type UserInfoResp struct {
	Name string `json:"name"`
	Role string `json:"role"`
}
