// Code generated by goctl. DO NOT EDIT.
package types

type UserLoginReq struct {
	StuffCode string `json:"stuffCode"`
	Password  string `json:"password"`
}

type UserLoginResp struct {
	Role        string `json:"role"`
	AccessToken string `json:"accessToken"`
}

type UserLogoutReq struct {
}

type UserLogoutResp struct {
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	Id        string `json:"id"`
	StuffCode string `json:"stuffCode"`
	Name      string `json:"name"`
	Role      string `json:"role"`
}

type LoadInfoReq struct {
	UserInfoTable []byte `json:"userInfoTable"`
}

type LoadInfoResp struct {
	OutputTable []byte `json:"outputTable"`
}
