// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"Table/app/user/cmd/rpc/internal/logic"
	"Table/app/user/cmd/rpc/internal/svc"
	"Table/app/user/cmd/rpc/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *pb.UserRegisterReq) (*pb.UserRegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) Login(ctx context.Context, in *pb.UserLoginReq) (*pb.UserLoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) GetInfo(ctx context.Context, in *pb.UserInfoReq) (*pb.UserInfoResp, error) {
	l := logic.NewGetInfoLogic(ctx, s.svcCtx)
	return l.GetInfo(in)
}
