// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	wage "Table/app/financial/cmd/api/internal/handler/wage"
	"Table/app/financial/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/cal",
				Handler: wage.CalWageHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/wage"),
	)
}
